DEFAULT_PARAMS = (1000, 1e-4, 0.4, 1e-5, 1e5, 1e1, 3, 0.5, 1)

CAT_COLUMNS = [
    'NUMBER', 'ID_PARENT', 'FLUX_ISO', 'FLUXERR_ISO', 'MAG_ISO', 'MAGERR_ISO', 'BACKGROUND', 'ISOAREA_IMAGE', 'ISOAREAF_IMAGE',
    'XPEAK_IMAGE', 'YPEAK_IMAGE', 'X_IMAGE', 'Y_IMAGE', 'X_IMAGE_DBL', 'Y_IMAGE_DBL',
    'X_WORLD', 'Y_WORLD', 'A_IMAGE', 'B_IMAGE', 'THETA_IMAGE', 'ERRA_IMAGE', 'ERRB_IMAGE',
    'ERRTHETA_IMAGE', 'XWIN_IMAGE', 'YWIN_IMAGE', 'XWIN_WORLD', 'YWIN_WORLD', 'X2WIN_IMAGE', 'Y2WIN_IMAGE',
    'X2WIN_WORLD', 'Y2WIN_WORLD', 'AWIN_IMAGE', 'BWIN_IMAGE', 'THETAWIN_IMAGE', 'AWIN_WORLD', 'BWIN_WORLD',
    'THETAWIN_WORLD', 'MU_THRESHOLD', 'FLAGS', 'FWHM_IMAGE', 'ELONGATION', 'ELLIPTICITY', 'CLASS_STAR'
]
